# -*- coding: utf-8 -*-
"""questao5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YOd3ap-4VzSxEPgjq4Ms8JXmBdkXVSuQ
"""

def inverte_string(string):
  inverte_string = ""
  for i in range(len(string) - 1, -1, -1):
    inverte_string += string[i]
  return inverte_string

string = input("Insira a string: ")

print("A string invertida é:", inverte_string(string))