# -*- coding: utf-8 -*-
"""questao1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zWQn2kpYO1FzeBJa4PPxIGAFYgm2dY0N
"""

indice = 13
soma = 0
k = 0

while k < indice:
  k = k + 1
  soma = soma + k

print("O valor da variável soma é:", soma)