# -*- coding: utf-8 -*-
"""questao2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NL_aC-yMsPYX1qOnNKENOjhN2C_ay3v4
"""

import numpy as np

busca = np.random.randint(0, 10000)

def verifica_fibonacci(busca):
    a = 0
    b = 1
    while a <= busca:
        if a == busca:
            return print(f"{busca} pertence à sequência de Fibonacci.")
        a = b
        b = a + b

    return print(f"{busca} não pertence à sequência de Fibonacci.")

verifica_fibonacci(busca)